markdown: kramdown
highlighter: pygments
permalink: blog/:year/:month/:day/:title.html
paginate: 6
paginate_path: page/:num

blog:
    name:lunabird's Blog                                 
    description:学习和生活                               
    title:lunabird
    url:http://lunabird.github.io/blog/
    duoshuo:                                            
    tongji:                                              
    qiniu:                                               
author:
    name:lunabird
    email:252570154@qq.com
    weibo:http://weibo.com/u/1704284104
    github:https://github.com/lunabird
    logo:                                                # logo地址
    douban:
        name:                                            # 豆瓣地址名称
        key:                                             # 豆瓣API Key